import { Head, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

export default function ClassesIndex({ classes = [] }) {
    const form = useForm({ student_ids: [], class_id: '' });
    const toggle = (id) => form.setData('student_ids', form.data.student_ids.includes(id) ? form.data.student_ids.filter((item) => item !== id) : [...form.data.student_ids, id]);
    return <><Head title="Classes and students" /><div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-400">Academic structure</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Classes and students</h2><p className="mt-2 text-sm text-slate-500">Review class rosters and move selected students to their next class.</p></div><form onSubmit={(event) => { event.preventDefault(); form.post('/classes/promote', { preserveScroll: true, onSuccess: () => form.setData('student_ids', []) }); }} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="text-sm font-medium text-slate-700">Promote selected to<select required value={form.data.class_id} onChange={(event) => form.setData('class_id', event.target.value)} className="mt-1 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5"><option value="">Select class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button disabled={form.processing || !form.data.student_ids.length} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Move {form.data.student_ids.length || ''} selected</button></div></form><div className="grid gap-5 lg:grid-cols-2">{classes.map((item) => <section key={item.id} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold text-slate-900">{item.name}</h3><p className="text-sm text-slate-500">{item.level || 'Class'}{item.branch ? ` · ${item.branch}` : ''}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{item.students.length} students</span></div><div className="mt-4 space-y-2">{item.students.length ? item.students.map((student) => <label key={student.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" checked={form.data.student_ids.includes(student.id)} onChange={() => toggle(student.id)} /><span><span className="block font-semibold text-slate-900">{student.name}</span><span className="text-xs text-slate-500">{student.admission_no || 'No admission number'}</span></span></label>) : <p className="text-sm text-slate-500">No students assigned.</p>}</div></section>)}</div></div></>;
}

ClassesIndex.layout = AuthenticatedLayout;