import { Head, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

const inputClass = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-900';

export default function FinanceIndex({ feeTypes = [], structures = [], students = [], invoices, summary = {}, canManageFeeSetup = false }) {
    const typeForm = useForm({ name: '', code: '' });
    const structureForm = useForm({ fee_type_id: '', amount: '', due_date: '' });
    const invoiceForm = useForm({ student_id: '', fee_structure_ids: [], discount: '', due_date: '' });
    const paymentForm = useForm({ invoice_id: '', amount: '', method: 'cash', reference: '', paid_at: '', notes: '' });

    const submitType = (event) => { event.preventDefault(); typeForm.post('/finance/fee-types', { preserveScroll: true, onSuccess: () => typeForm.reset() }); };
    const submitStructure = (event) => { event.preventDefault(); structureForm.post('/finance/structures', { preserveScroll: true, onSuccess: () => structureForm.reset() }); };
    const submitInvoice = (event) => { event.preventDefault(); invoiceForm.post('/finance/invoices', { preserveScroll: true, onSuccess: () => invoiceForm.reset() }); };
    const submitPayment = (event) => { event.preventDefault(); paymentForm.post(`/finance/invoices/${paymentForm.data.invoice_id}/payments`, { preserveScroll: true, onSuccess: () => paymentForm.reset() }); };
    const toggleStructure = (id) => invoiceForm.setData('fee_structure_ids', invoiceForm.data.fee_structure_ids.includes(id) ? invoiceForm.data.fee_structure_ids.filter((item) => item !== id) : [...invoiceForm.data.fee_structure_ids, id]);
    const selectedInvoice = invoices?.data?.find((invoice) => String(invoice.id) === String(paymentForm.data.invoice_id));

    return <>
        <Head title="Accountant portal" />
        <div className="space-y-6">
            <div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-400">Accountant portal</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Fees, invoices and payments</h2><p className="mt-2 text-sm text-slate-500">Administrators define fee setup. Accountants issue invoices and record payments.</p></div>
            <div className="grid grid-cols-1 gap-3 md:grid-cols-3">{[['Invoiced', summary.invoiced], ['Collected', summary.collected], ['Outstanding', summary.outstanding]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">GHS {Number(value || 0).toFixed(2)}</p></div>)}</div>
            <div className="grid gap-6 xl:grid-cols-3">
                <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-slate-900">Fee types</h3><p className="mt-1 text-xs text-slate-500">Admin or principal only</p></div><span className="rounded-full bg-indigo-100 px-2 py-1 text-xs font-semibold text-indigo-700">{canManageFeeSetup ? 'Setup access' : 'Read only'}</span></div>{canManageFeeSetup && <form onSubmit={submitType} className="mt-4 space-y-3"><input required placeholder="Tuition" value={typeForm.data.name} onChange={(event) => typeForm.setData('name', event.target.value)} className={inputClass} /><input required placeholder="TUITION" value={typeForm.data.code} onChange={(event) => typeForm.setData('code', event.target.value)} className={inputClass} /><button className="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Add fee type</button></form>}<div className="mt-5 space-y-2">{feeTypes.map((type) => <div key={type.id} className="rounded-xl bg-slate-50 px-3 py-2 text-sm">{type.name} <span className="text-xs text-slate-400">{type.code}</span></div>)}</div></section>
                <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-slate-900">Fee structures</h3><p className="mt-1 text-xs text-slate-500">Admin or principal only</p></div><span className="rounded-full bg-indigo-100 px-2 py-1 text-xs font-semibold text-indigo-700">{canManageFeeSetup ? 'Setup access' : 'Read only'}</span></div>{canManageFeeSetup && <form onSubmit={submitStructure} className="mt-4 space-y-3"><select required value={structureForm.data.fee_type_id} onChange={(event) => structureForm.setData('fee_type_id', event.target.value)} className={inputClass}><option value="">Select fee type</option>{feeTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><input required type="number" min="0" step="0.01" placeholder="Amount (GHS)" value={structureForm.data.amount} onChange={(event) => structureForm.setData('amount', event.target.value)} className={inputClass} /><input type="date" value={structureForm.data.due_date} onChange={(event) => structureForm.setData('due_date', event.target.value)} className={inputClass} /><button className="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Add structure</button></form>}<div className="mt-5 space-y-2">{structures.map((structure) => <label key={structure.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span><input type="checkbox" checked={invoiceForm.data.fee_structure_ids.includes(structure.id)} onChange={() => toggleStructure(structure.id)} className="mr-2" />{structure.fee_type}</span><span>GHS {Number(structure.amount).toFixed(2)}</span></label>)}</div></section>
                <form onSubmit={submitInvoice} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-semibold text-slate-900">Create invoice</h3><p className="mt-1 text-xs text-slate-500">Accountant operational workflow</p><div className="mt-4 space-y-3"><select required value={invoiceForm.data.student_id} onChange={(event) => invoiceForm.setData('student_id', event.target.value)} className={inputClass}><option value="">Select student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.first_name} {student.last_name} · {student.admission_no}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Discount" value={invoiceForm.data.discount} onChange={(event) => invoiceForm.setData('discount', event.target.value)} className={inputClass} /><input type="date" value={invoiceForm.data.due_date} onChange={(event) => invoiceForm.setData('due_date', event.target.value)} className={inputClass} /><button className="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Issue invoice</button></div></form>
            </div>
            <form onSubmit={submitPayment} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold text-slate-900">Record payment</h3><p className="mt-1 text-xs text-slate-500">Accountant operational workflow</p></div>{selectedInvoice && <span className="text-sm text-slate-500">Balance: GHS {Number(selectedInvoice.balance).toFixed(2)}</span>}</div><div className="mt-4 grid gap-3 md:grid-cols-5"><select required value={paymentForm.data.invoice_id} onChange={(event) => paymentForm.setData('invoice_id', event.target.value)} className={inputClass}><option value="">Select invoice</option>{invoices?.data?.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.invoice_no} · {invoice.student}</option>)}</select><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={paymentForm.data.amount} onChange={(event) => paymentForm.setData('amount', event.target.value)} className={inputClass} /><select value={paymentForm.data.method} onChange={(event) => paymentForm.setData('method', event.target.value)} className={inputClass}><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="mobile_money">Mobile Money</option><option value="card">Card</option><option value="other">Other</option></select><input placeholder="Reference" value={paymentForm.data.reference} onChange={(event) => paymentForm.setData('reference', event.target.value)} className={inputClass} /><button className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Record payment</button></div></form>
            <section className="overflow-x-auto rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-semibold text-slate-900">Invoices</h3><table className="mt-4 w-full min-w-160 text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-3 py-3">Invoice</th><th className="px-3 py-3">Student</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Paid</th><th className="px-3 py-3">Balance</th><th className="px-3 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{invoices?.data?.length ? invoices.data.map((invoice) => <tr key={invoice.id}><td className="px-3 py-4 font-semibold">{invoice.invoice_no}</td><td className="px-3 py-4">{invoice.student}</td><td className="px-3 py-4">GHS {Number(invoice.total).toFixed(2)}</td><td className="px-3 py-4">GHS {Number(invoice.paid).toFixed(2)}</td><td className="px-3 py-4">GHS {Number(invoice.balance).toFixed(2)}</td><td className="px-3 py-4 capitalize">{invoice.status}</td></tr>) : <tr><td colSpan="6" className="px-3 py-8 text-center text-slate-500">No invoices created yet.</td></tr>}</tbody></table></section>
        </div>
    </>;
}

FinanceIndex.layout = AuthenticatedLayout;
