import { Head, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout';

const inputClass = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-900';

export default function ProfileIndex({ user }) {
    const profile = useForm({ name: user?.name || '', email: user?.email || '' });
    const password = useForm({ current_password: '', password: '', password_confirmation: '' });
    return <><Head title="Profile settings" /><div className="mx-auto max-w-3xl space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-400">Account</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Profile settings</h2><p className="mt-2 text-sm text-slate-500">Update your account details and portal password.</p></div><form onSubmit={(event) => { event.preventDefault(); profile.put('/profile'); }} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-semibold text-slate-900">Profile</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Name<input required value={profile.data.name} onChange={(event) => profile.setData('name', event.target.value)} className={`${inputClass} mt-1`} />{profile.errors.name && <span className="mt-1 block text-xs text-rose-600">{profile.errors.name}</span>}</label><label className="text-sm font-medium text-slate-700">Email<input required type="email" value={profile.data.email} onChange={(event) => profile.setData('email', event.target.value)} className={`${inputClass} mt-1`} />{profile.errors.email && <span className="mt-1 block text-xs text-rose-600">{profile.errors.email}</span>}</label></div><button disabled={profile.processing} className="mt-4 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Save profile</button></form><form onSubmit={(event) => { event.preventDefault(); password.put('/profile/password', { onSuccess: () => password.reset() }); }} className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-semibold text-slate-900">Change password</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{[['current_password', 'Current password'], ['password', 'New password'], ['password_confirmation', 'Confirm password']].map(([field, label]) => <label key={field} className="text-sm font-medium text-slate-700">{label}<input required type="password" value={password.data[field]} onChange={(event) => password.setData(field, event.target.value)} className={`${inputClass} mt-1`} />{password.errors[field] && <span className="mt-1 block text-xs text-rose-600">{password.errors[field]}</span>}</label>)}</div><button disabled={password.processing} className="mt-4 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Change password</button></form></div></>;
}

ProfileIndex.layout = AuthenticatedLayout;